### PR TITLE
Feat: add dodoc to autogenerate all the methods documentation

### PR DESCRIPTION
**Pull request by octavioamu**
### Purpose for this PR
Configure https://www.npmjs.com/package/@primitivefi/hardhat-dodoc to autogenerate all the methods documentation
If NatSpec is followed then the docs will be even better
ex: 
```
/// @notice Does another thing when the function is called.
/// @dev More info about doing another thing when the function is called.
/// @param num A random number
/// @return A random variable

```
example of what we get https://github.com/windranger-io/windranger-treasury/blob/feat/auto-documentation/docs/documentation/bond/BondMediator.md

### CODE REVIEW

**Comment by CjHare** [comment]
@octavioamu do you actually use the autogenerated docs, rather than looking at the code?

**Comment by octavioamu** [comment]
> @octavioamu do you actually use the autogenerated docs, rather than looking at the code?

yes I feel is more easy to understand what the contract do methods with their inputs and outputs. For FE implementation I feel facilitates the work and take out some needs of asking the solidity devs when we don't get what is going on.

**Comment by CjHare** [comment]
tbh the average NatSpec comment tends to be not helpful i.e. conveying no real detail beyond what you know from the function signature.

question: is merely have the function signature converted into the HTML meaningful? ...or do you actually need those quality comments?

**Comment by CjHare** [comment]
Ah, you've got the generated docs checked in as part of the PR.

Raises an interesting question. @octavioamu would you use the web browser to see the docs?

What I'm thinking ...as there's no way to guarantee the docs are correct (as users can prevent local precommit hooks from executing), it would be better to have the generation tooling present and leave for people to generate locally 🤔 

wdyt?

**Comment by CjHare** [comment]
https://www.npmjs.com/package/solidity-docgen

Might be better to use that instead, due to usage numbers.

**Comment by CjHare** [comment]
Closed by https://github.com/windranger-io/windranger-treasury/pull/327

**Pull request closed without merging**
