### PR TITLE
spec: activation bars for sequence diagram

### PR DESCRIPTION
**Pull request by CjHare**
### Purpose for this PR

Sequence diagrams usually have activation bars to denote the lifespan of activities (operations), this change adds them using the `activate` & `deactivate` PlantUML keywords.

The other option is to use `++` and `--` shorthand, which would have a different affect on the reading of the code (also with that shorthand, it only applies to the receiver of the function, making it difficult to get an activation bar on Alice).

Let me know what you think (I suspect the extra lines reduce readability 🤔)

### CODE REVIEW

**Review by shahankhatch — APPROVED** [review]
lgtm

issue: there are some visual artifacts. Examples:
1. activations reaching into the optional box, which makes it look like snapshot is activated through the pass and into the fail conditionals
2. some activations extend past an arrow which makes it look like the object continues to do something

thought: such issues are not significant enough to block this PR

**Comment by CjHare** [comment]
> 1. activations reaching into the optional box, which makes it look like snapshot is activated through the pass and into the fail conditionals

That's down to the snapshot actor not being deactivated after it's call.
There is a rendering issue (imprecision) with PlantUML and the activation / termination of activities. You can't reliably re-start an activity bar in the sub-option and the beginning of it's sub-box.

There are three option
1.  An activity bar running through the options, terminating on the last call at the bottom `else` clause.
2.  Wonk start positions for every following `else` option.
3.  No activity bar when you enter into the `group` element.

Which of those options look nicer? ...either option one or three (don't mind which)

> 2. some activations extend past an arrow which makes it look like the object continues to do something

Interestingly the ordering of `activate` `deactivate` was causing those visual artefacts, fixed.

**Comment by shahankhatch** [comment]
The fixes look good. 

suggestion: I prefer option 3.

**Comment by CjHare** [comment]
As there's no other preferences state @shahankhatch option 3 it is 😁

**Pull request merged**
