### PR TITLE
fix: timestamps to uint128 on StakingPool contracts

### PR DESCRIPTION
**Pull request by grezle**
### Purpose for this PR

Sets type to uint128 for timestamp values

### CODE REVIEW

**Comment by CjHare** [comment]
Ah, this change will affect struct packing 🤔 

@afkbyte what are your thoughts on widening the timestamps?

**Comment by CjHare** [comment]
LGTM, the tests & framework also need updating ...but I've put that into another ticket https://github.com/windranger-io/windranger-treasury/issues/312

**Comment by grezle** [comment]
> Ah, this change will affect struct packing`

Oh my bad, scratch this 😅 

I think the only reason I had to make the change was to get the deploy script to run, its using the `latestBlock.timestamp` as the `epochStartTimestamp` which was throwing errors. I remember reading that any uint smaller than 256 is treat as a 256 by solidity, is that bad information?

**Comment by grezle** [comment]
> Ah, this change will affect struct packing`

Oh my bad, scratch this 😅 

I think the only reason I had to make the change was to get the deploy script to run, its using the `latestBlock.timestamp` as the `epochStartTimestamp` which was throwing errors. I remember reading that any uint smaller than 256 is treat as a 256 by solidity, is that bad information?

**Comment by CjHare** [comment]
> > Ah, this change will affect struct packing`
> 
> Oh my bad, scratch this 😅
> 
> I think the only reason I had to make the change was to get the deploy script to run, its using the `latestBlock.timestamp` as the `epochStartTimestamp` which was throwing errors. I remember reading that any uint smaller than 256 is treat as a 256 by solidity, is that bad information?
It is true ...some of the time 😉 

A word in Solidity is 256bits.
There is a gas optimisation call variable packing (for fields in a contract) and struct packing (for structs), where if there are multiple variables together in size smaller than 256 bits, they can be stored together to save gas (single read & write vs multiple)
e.g. https://www.maxgrok.com/posts/one-hundred-and-nineth-post#1-use-structs-packing-source-a-hrefhttpscryptozombiesioenlesson3chapter4cryptozombiesa

**Comment by CjHare** [comment]
In Solidity timestamps (from `block.timestamp`) is uint256, so in theory using anything less could cause loss ...but that's a long way in the future problem..

**Comment by aodhgan** [comment]
I think maybe we should consider moving to 64 bits (from 32 bits) if the staking pool contracts are expected to run to 2038. https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by aodhgan** [comment]
closing since i dont think realistically the pools will run until 2038, so overflow not a problem sufficient enough to worry about to forgo struct packing gas savings.

**Pull request closed without merging**
